theme: minima
title: My Site
description: A brief description of my site
baseurl: ""
url: "https://your-github-FogOff.github.io/FogOfWar"
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude these files from the site build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Build settings
future: true
